import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/NavBar';
import Options from '@/util/options';
import BottomNav from '@/components/BottomNav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <meta name="viewport" content="viewport-fit=cover" />
      <body className={inter.className}>
        <NavBar siteName={Options.SITE_NAME || 'Wins Pool'} />
        {children}
        <BottomNav />
      </body>
    </html>
  );
}
